#!/bin/bash

FILES=".gitconfig .tmux.conf .vimrc .xinitrc .Xmodmap .Xresources .zlogin .zpreztorc .zshrc"
DOTFILE_DIR=$(pwd)

for FILE in $FILES; do
  ln -s $DOTFILE_DIR/$FILE ~/$FILE
done

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

mkdir ~/.i3
ln -s $DOTFILE_DIR/.i3/config ~/.i3/config
